"""empty message

Revision ID: 10d3c429f4ac
Revises: 4b626c6c884c
Create Date: 2014-08-25 00:09:04.970434

"""

# revision identifiers, used by Alembic.
revision = '10d3c429f4ac'
down_revision = '4b626c6c884c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('bill', 'contents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('contents', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('bill', 'content')
    ### end Alembic commands ###
