"""empty message

Revision ID: 1445af1b77fb
Revises: 4eac3a857f6
Create Date: 2014-08-25 00:01:25.317457

"""

# revision identifiers, used by Alembic.
revision = '1445af1b77fb'
down_revision = '4eac3a857f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
