"""empty message

Revision ID: 1a3ea64d34bc
Revises: 1445af1b77fb
Create Date: 2014-08-25 00:04:17.035036

"""

# revision identifiers, used by Alembic.
revision = '1a3ea64d34bc'
down_revision = '1445af1b77fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
