"""empty message

Revision ID: 30e81b3a9bed
Revises: 10d3c429f4ac
Create Date: 2014-08-27 04:27:02.811325

"""

# revision identifiers, used by Alembic.
revision = '30e81b3a9bed'
down_revision = '10d3c429f4ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('like', sa.Integer(), nullable=True))
    op.drop_column('bill', 'status')
    op.drop_column('bill', 'content')
    op.drop_column('bill', 'proposed_date')
    op.drop_column('bill', 'name')
    op.drop_column('bill', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('proposed_date', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('content', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bill', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('bill', 'like')
    ### end Alembic commands ###
