"""empty message

Revision ID: 326c1547fcca
Revises: 51d5a01e0552
Create Date: 2014-08-17 03:25:51.879531

"""

# revision identifiers, used by Alembic.
revision = '326c1547fcca'
down_revision = '51d5a01e0552'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('login_email', sa.String(length=255), nullable=True))
    op.add_column('login', sa.Column('login_name', sa.String(length=255), nullable=True))
    op.add_column('login', sa.Column('login_rpw', sa.String(length=255), nullable=True))
    op.drop_column('login', 'name')
    op.drop_column('login', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('login', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('login', 'login_rpw')
    op.drop_column('login', 'login_name')
    op.drop_column('login', 'login_email')
    ### end Alembic commands ###
