"""empty message

Revision ID: 32a88b4c28dc
Revises: 4661016a95e5
Create Date: 2014-08-24 21:50:55.639708

"""

# revision identifiers, used by Alembic.
revision = '32a88b4c28dc'
down_revision = '4661016a95e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('bill_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'bill_id')
    ### end Alembic commands ###
