"""empty message

Revision ID: 49e8edb97204
Revises: 326c1547fcca
Create Date: 2014-08-18 00:35:02.479224

"""

# revision identifiers, used by Alembic.
revision = '49e8edb97204'
down_revision = '326c1547fcca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'login_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('login_id', mysql.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
