"""empty message

Revision ID: 4b626c6c884c
Revises: 1a3ea64d34bc
Create Date: 2014-08-25 00:06:17.135268

"""

# revision identifiers, used by Alembic.
revision = '4b626c6c884c'
down_revision = '1a3ea64d34bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('contents', sa.String(length=255), nullable=True))
    op.drop_column('bill', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('bill', 'contents')
    ### end Alembic commands ###
