"""empty message

Revision ID: 4eac3a857f6
Revises: 32a88b4c28dc
Create Date: 2014-08-24 23:57:15.779010

"""

# revision identifiers, used by Alembic.
revision = '4eac3a857f6'
down_revision = '32a88b4c28dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('bill', 'contents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('contents', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('bill', 'content')
    ### end Alembic commands ###
