"""empty message

Revision ID: 51d5a01e0552
Revises: 3a2691376f43
Create Date: 2014-08-17 03:14:47.708830

"""

# revision identifiers, used by Alembic.
revision = '51d5a01e0552'
down_revision = '3a2691376f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('login', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('login', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'name')
    op.drop_column('login', 'email')
    op.drop_column('login', 'date_created')
    ### end Alembic commands ###
