"""empty message

Revision ID: 2d652985277a
Revises: 36b0e64c4425
Create Date: 2014-08-19 04:26:02.488943

"""

# revision identifiers, used by Alembic.
revision = '2d652985277a'
down_revision = '36b0e64c4425'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('like', sa.Integer(), nullable=True))
    op.drop_column('article', 'count')
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    op.drop_column('comment', 'count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('comment', 'like')
    op.add_column('article', sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('article', 'like')
    ### end Alembic commands ###
